-- Sano & Sabroso — esquema real (reemplaza localStorage)
-- Ver plan: /Users/genesisortiz/.claude/plans/transient-nibbling-peach.md

create extension if not exists pgcrypto;

create table if not exists dishes (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text not null,
  price numeric(10,2) not null,
  image_url text not null,
  available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null unique,
  last_address text not null default '',
  last_order_at timestamptz not null default now(),
  order_count integer not null default 0
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  address text not null,
  items jsonb not null,
  payment_method text not null,
  notes text not null default '',
  status text not null default 'pendiente',
  total numeric(10,2) not null,
  created_at timestamptz not null default now()
);

alter table dishes enable row level security;
alter table customers enable row level security;
alter table orders enable row level security;

-- Sin políticas públicas en las tablas: todo el acceso pasa por las
-- funciones serverless (/api/*), que usan la service-role key del lado del
-- servidor y por lo tanto ignoran RLS. El anon key del cliente no tiene
-- ningún permiso sobre dishes/customers/orders.

-- Bucket de Storage para las fotos de los platos. Público de lectura (el
-- menú público carga las imágenes directo desde el navegador sin pasar por
-- nuestra API); la escritura solo ocurre desde /api/upload con la
-- service-role key, que ignora RLS igual que en las tablas.
insert into storage.buckets (id, name, public)
values ('dish-images', 'dish-images', true)
on conflict (id) do nothing;
